- name: "Export data pump"
  shell: expdp "{{ user }}"/"{{ PRE_password }}"@"{{ PRE_service_name }}" directory="{{ PRE_dpump_dir }}" dumpfile="{{ schema }}_{{ PRE_dumpfile }}" content="{{ content }}" schemas="{{ schema }}" exclude=STATISTICS,DB_LINK
  environment: "{{ oracle_env }}"

- name: "Fetching file"
  fetch:
    src: "{{ PRE_dpump_dir_path }}{{ schema }}_{{ PRE_dumpfile }}"
    dest: "{{ dpump_dir_local_path }}"

- name: "Delete data pump"
  file:
    path: "{{ PRE_dpump_dir_path }}{{ schema }}_{{ PRE_dumpfile }}"
    state: absent
